require("alpha").setup(astronvim.user_plugin_opts("plugins.alpha", {
  layout = {
    { type = "padding", val = vim.fn.max { 2, vim.fn.floor(vim.fn.winheight(0) * 0.2) } },
    {
      type = "text",
      val = astronvim.user_plugin_opts("header", {
        "        .                                                        . ",
        "        .n                   .                 .                  n. ",
        "  .   .dP                  dP                   9b                 9b.    . ",
        " 4    qXb         .       dX                     Xb       .        dXp     t ",
        "dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb ",
        "9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP ",
        " 9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP ",
        "  `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP' ",
        "    `9XXXXXXXXXXXP' `9XX'          `98v8P'          `XXP' `9XXXXXXXXXXXP' ",
        "        ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~ ",
        "                        )b.  .dbo.dP'`v'`9b.odb.  .dX( ",
        "                      ,dXXXXXXXXXXXb     dXXXXXXXXXXXb. ",
        "                     dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb ",
        "                    dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb ",
        "                    9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP ",
        "                     `'      9XXXXXX(   )XXXXXXP      `' ",
        "                              XXXX X.`v'.X XXXX ",
        "                              XP^X'`b   d'`X^XX ",
        "                              X. 9  `   '  P )X ",
        "                              `b  `       '  d' ",
        "                               `             ' ", }, false),
      opts = { position = "center", hl = "DashboardHeader" },
    },
    -- { type = "padding", val = 5 },
    -- {
    --   type = "group",
    --   val = {
    --     astronvim.alpha_button("LDR f f", "  Find File  "),
    --     astronvim.alpha_button("LDR f o", "  Recents  "),
    --     astronvim.alpha_button("LDR f w", "  Find Word  "),
    --     astronvim.alpha_button("LDR f n", "  New File  "),
    --     astronvim.alpha_button("LDR f m", "  Bookmarks  "),
    --     astronvim.alpha_button("LDR S l", "  Last Session  "),
    --   },
    --   opts = { spacing = 1 },
    -- },
  },
  opts = { noautocmd = true },
}))
